In [ ]:
import torch
from torch_geometric.datasets import QM9
from torch_geometric.loader import DataLoader
from utils.rotation_utils import rotate_positions, superfib_augment_batch
from utils.learned_variance_utils import get_orbit_variance



In [ ]:
#SET PARAMETERS
TARGET = 10   # G @ 298.15K
torch.manual_seed(42)
dataset = QM9(root='data/QM9')

dataset.data.y = dataset.data.y[:, TARGET].unsqueeze(-1)





/var/folders/wm/yc9mt70x4k369qvxkpnbz6rr0000gp/T/ipykernel_36512/2913631767.py:8: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  dataset.data.y = dataset.data.y[:, TARGET].unsqueeze(-1)


In [50]:
loader = DataLoader(dataset, batch_size=1, shuffle=True)

In [54]:
for batch in loader:
    print(batch.pos)
    print(batch.z)
    print(batch.batch)
    print(batch.y)
    pos = batch.pos
    z = batch.z
    y = batch.y
    batch_indices = batch.batch
    print(superfib_augment_batch(pos, z, y, batch_indices, 4))
    break

tensor([[-7.9740e-01,  1.2272e+00,  1.6800e-02],
        [ 1.8940e-01,  6.3200e-02,  1.2000e-03],
        [ 1.1557e+00,  6.1600e-02, -1.2338e+00],
        [ 2.3564e+00, -6.5590e-01, -6.9550e-01],
        [ 3.5054e+00, -1.3030e+00, -9.9680e-01],
        [ 4.1151e+00, -1.7061e+00,  1.4160e-01],
        [ 3.3468e+00, -1.3139e+00,  1.2504e+00],
        [ 2.3236e+00, -7.0010e-01,  7.2420e-01],
        [ 1.1049e+00, -1.5600e-02,  1.2671e+00],
        [-2.7050e-01,  2.1875e+00,  6.0500e-02],
        [-1.4221e+00,  1.2297e+00, -8.8260e-01],
        [-1.4639e+00,  1.1722e+00,  8.8370e-01],
        [-3.7500e-01, -8.7670e-01, -3.9800e-02],
        [ 6.9710e-01, -4.1110e-01, -2.1070e+00],
        [ 1.4075e+00,  1.0910e+00, -1.5228e+00],
        [ 4.0193e+00, -1.5657e+00, -1.9084e+00],
        [ 1.3619e+00,  9.9070e-01,  1.6235e+00],
        [ 6.3170e-01, -5.4310e-01,  2.0988e+00]])
tensor([6, 6, 6, 6, 6, 8, 7, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0